### ISSUE TITLE
ToscaIDCInterface uses Liferay-IAM services even for tokens not handled by Liferay-IAM

### ISSUE THREAD

**Issue by tzok** [indigo-dc/APIServerDaemon#39]
In `ToscaIDCInterface#getStatus` there is the following:
```java
        String tToken = taskTokenSubject[0];
        String tSubject = taskTokenSubject[1];
        LOG.debug("Last token: " + tToken + "'" + LS
                + "Subject   : " + tSubject + "'");
        if (tSubject.length() > 0) {
            // Token having a subject require a fresh token from PTV
            tToken = getPTVToken(tSubject);
            LOG.debug("PTV Token is: '" + tToken + "'");
        }
```

This must be changed. The current implementation of PTV is based on Liferay's `get-token` service. But there are users of FutureGateway who never log into Liferay. For them, call to `getPTVToken` result in an empty IAM token and eventually tasks being frozen in `SUBMITTED` state even though they are already finished.

In the code snippet above, the token is already there in the `tToken` variable, so there is no need to call `getPTVToken`

CC: @mupsnc @smamczak

**Comment by ricsxn** [comment]
ToscaIDC is expressly coupled with IAM because the Orchestrator uses IAM and by original architecture design, FG does not deal directly with IAM but delegates this operation to the PTV service; no matter if it is LiferayIAM or another system; this is configurable in file:

web/WEB-INF/classes/it/infn/ct/ToscaIDC.properties

where the following parameters can be configured:

fgapisrv_ptvendpoint - The PTV service endpoint
fgapisrv_ptvuser    - PTV basic authentication username
fgapisrv_ptvpass   - PTV basic authentication username

At the moment the get-token service name is hardcoded, BTW another parameter will be added for this. Of course this setting has a global scope for the APIServerDaemon.
PTV is used by ToscaIDC for ALL operations (deployment creation and check)
